image: cirrusci/flutter:stable  # Use a stable Flutter image

stages:
  - build
  - test
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "feat/tradly-shop-app"' # Trigger pipeline for specific branch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Trigger pipeline for merge requests

build_android:
  stage: build
  script:
    - flutter packages get # Install dependencies
    - flutter build apk --release # Build Android APK in release mode
  artifacts:
    paths:
      - build/app/outputs/apk/release/*.apk # Save APK as artifact


test:
  stage: test
  script:
    - flutter test # Run unit tests

