image: gbcr.io/cirruslabs/flutter

stages:
  - lints
  - test

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "feat/tradly-shop-app"' # Trigger pipeline for specific branch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Trigger pipeline for merge requests

lints:
  stage: lints
  before_script:
    - if [ -f reconfigure.sh ]; then bash reconfigure.sh; else echo "reconfigure.sh not found"; fi # Ensure script exists
  script:
    - flutter analyze || echo "Linting failed" # Run linting with error handling
  tags:
    - flutter

unit_tests:
  stage: test
  script:
    - flutter test --coverage || echo "Tests failed" # Run tests with error handling
  artifacts:
    paths:
      - coverage/lcov.info # Save coverage report
    reports:
      junit: test/test_results.xml # Save test results in JUnit format
  tags:
    - flutter
